name: Nodejs CD
on:
  push:
    tags:
      - 'v*'

jobs:
  docker-publish:
    name: Build & Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: tag
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)
      - name: Setting version number
        id: versionNumber
        env:
          versionNumber: "${{steps.tag.outputs.VERSION}}"
        run: echo $versionNumber
      - name: Updating version number to $versionNumber
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./VERSION
          contents: $versionNumber
          write-mode: overwrite
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: jamesgawn/ddns-route53-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{env.versionNumber}}"