name: Publish
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  ghcr-publication:
    name: Build & Publish (GHCR)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/jamesgawn/ddns-service
          tag-semver: |
            {{version}}
      - name: Get the version
        id: tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)
      - name: Updating version number to ${{ env.versionNumber }}
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./VERSION
          contents: ${{ steps.tag.outputs.tag }}
          write-mode: overwrite
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
