name: Node.js CD
on:
  push:
    tags:
      - 'v*'

jobs:
  docker-publish:
    name: Build & Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: tag
        run: echo ::set-env name=versionNumber::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)
      - name: Updating version number to ${{ env.versionNumber }}
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./VERSION
          contents: ${{ env.versionNumber }}
          write-mode: overwrite
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: jamesgawn/ddns-route53-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.versionNumber }}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [docker-publish]
    steps:
      - name: Send SSM Upgrade Command
        run: aws ssm send-command --document-name ddns-service-upgrade --targets Key=tag:Name,Values=ddns-service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-2"